type sum :: Type -> Type -> Type =
  lam A. lam B. all C. (A -> C) -> (B -> C) -> C
val Left : all A. all B. A -> sum A B
val Right : all A. all B. B -> sum A B
val case : all A. all B. sum A B -> (all C. (A -> C) -> (B -> C) -> C)
val sum :
  {Left : all A. all B. A -> sum A B; Right : all A. all B. B -> sum A B;
   case : all A. all B. sum A B -> (all C. (A -> C) -> (B -> C) -> C)}
type Sum =
  exi sum1 :: Type -> Type -> Type.
    {Left : all A. all B. A -> sum1 A B; Right : all A. all B. B -> sum1 A B;
     case : all A. all B. sum1 A B -> (all C. (A -> C) -> (B -> C) -> C)}
val Sum : Sum
val <sum1,sum> =
  {Left : all A. all B. A -> sum1 A B; Right : all A. all B. B -> sum1 A B;
   case : all A. all B. sum1 A B -> (all C. (A -> C) -> (B -> C) -> C)}
type bi = sum1 bool int
val x : bi
val y : bi
val neg : bi -> bi
type Sum1 :: Type -> Type -> Type =
  lam A. lam B. exi sum2.
    {Left : A -> sum2; Right : B -> sum2;
     case : sum2 -> (all C. (A -> C) -> (B -> C) -> C)}
val Sum : all A. all B. Sum1 A B
val <bi1,bi> =
  {Left : bool -> bi1; Right : int -> bi1;
   case : bi1 -> (all C. (bool -> C) -> (int -> C) -> C)}
val x : bi1
val y : bi1
val neg : bi1 -> bi1
